dist: trusty
sudo: false

language: node_js
node_js:
  - '10'
cache: yarn

env:
  - REACT_APP_DOMAIN=ifs49f-poker.surge.sh REACT_APP_SOCKET_SERVER_URL=https://afternoon-gorge-59515.herokuapp.com/
  - REACT_APP_DOMAIN=poker4.fun REACT_APP_SOCKET_SERVER_URL=https://api.poker4.fun/ REACT_APP_GA_ID=UA-104177068-1

before_script:
  - openssl aes-256-cbc -K $encrypted_edffe1b3d92e_key -iv $encrypted_edffe1b3d92e_iv
    -in deploy_key.enc -out ~/.ssh/deploy_key -d
  - chmod 600 ~/.ssh/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/deploy_key
  - ssh-keyscan -p $SSH_PORT poker4.fun >> ~/.ssh/known_hosts

script:
  - yarn test --coverage
  - yarn build

# https://surge.sh/help/adding-a-200-page-for-client-side-routing
before_deploy:
  - cp ./build/index.html ./build/200.html

deploy:
  - provider: pages
    local_dir: ./coverage/
    github_token: $POKER_LCOV_REPORT_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: surge
    project: ./build/
    domain: ifs49f-poker.surge.sh
    skip_cleanup: true
    on:
      condition: $REACT_APP_DOMAIN = ifs49f-poker.surge.sh
  - provider: script
    script: rsync -r --delete-after -e "ssh -p $SSH_PORT" --quiet ./build/. deploy@poker4.fun:/websites/poker
    skip_cleanup: true
    on:
      condition: $REACT_APP_DOMAIN = poker4.fun
